blank_issues_enabled: false
contact_links:
  - name: Salesforce Inspector Reloaded Community Support
    url: https://github.com/tprouvot/Salesforce-Inspector-reloaded/discussions
    about: Please ask and answer questions here.
